run:
	clear
	node app.js

open:
	sublime app.js public/js/tagging.js views/* public/css/feedback.css

broswer:
	chrome http://localhost:3000

broswer2:
	chrome http://localhost:3000 http://localhost:3000