run:
	node app.js

open:
	sublime app.js views/* public/js/student.js public/js/instructor.js  public/css/feedback.css

broswer:
	chrome http://localhost:3000

broswer2:
	chrome http://localhost:3000 http://localhost:3000